version: '3.6'
services:

  app:
    container_name: richardalmonte.ml
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - 4000:4000
    restart: always
    command:
      sh -c "bundle install &&
            npm install &&
            npm run dev"